server:
  port: 8086

spring:
  application:
    name: auth-manager
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vimal-prabhakaran/eureka-discovery-service-info.git
          clone-on-start: true